version: '3'
services:
  back:
    volumes:
      - .:/app
    container_name: back-time-manager
    build: .
    env_file:
    - ./.env
    ports:
      - "4000:4000"
    depends_on:
      - db
    command: /app/entrypoint.sh
  db:
    image: postgres:latest
    container_name: db-time-manager
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}