version: '3'

services:
  back:
    image: webdesignpastor/time_manager_back
    build:
      context: ./time_manager
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - db
    command: /app/entrypoint.sh

  front:
    image: webdesignpastor/time_manager_front
    build:
      context: ./time_manager_app
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
