name: Nightly Database Backup

on:
  schedule:
    - cron: '0 1 * * *'
  push:
    branches:
      - master

jobs:
  backup-database:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Perform Database Backup
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
        PGUSER: ${{ secrets.PGUSER }}
        PGPASSWORD: ${{ secrets.PGPASSWORD }}
        PGDATABASE: ${{ secrets.PGDATABASE }}
      run: |
        # Save private key to file
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem

        # SSH into EC2 instance and perform the backup
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST <<-EOF
          # Perform the backup here. You might have a script ready for this, or perform the commands directly.
          # Example command for PostgreSQL:
          PGPASSWORD=$PGPASSWORD pg_dump -U $PGUSER $PGDATABASE > backup_$(date +%F).sql
        EOF
