name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    # Frontend: Build and Test
    - name: Build and test Frontend
      working-directory: ./time_manager_app
      run: |
        npm install
        npm run build
        npm run test

    # Backend: Build and Test
    - name: Build and test Backend
      working-directory: ./time_manager
      run: |
        # Add steps to build and test your Elixir API
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ${{ secrets.AWS_EC2_USER }}
        key: ${{ secrets.AWS_EC2_SSH_KEY }}
        script: |
          cd /path/to/your/app/on/ec2
          git pull
          docker-compose down
          docker-compose up --build -d
